CREATE TABLE IF NOT EXISTS BANK_ACCOUNT
(
    id         BIGSERIAL                NOT NULL PRIMARY KEY,
    owner      VARCHAR(100)             NOT NULL,
    balance    DOUBLE PRECISION         NOT NULL DEFAULT 0,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPE
(
    id   BIGSERIAL PRIMARY KEY,
    type VARCHAR(10)
);

INSERT INTO TRANSACTION_TYPE(id, type)
VALUES (1, 'DEPOSITO'),
       (2, 'RETIRO');

CREATE TABLE IF NOT EXISTS TRANSACTION
(
    id                  BIGSERIAL                NOT NULL PRIMARY KEY,
    bank_account_id     BIGINT                   NOT NULL
        CONSTRAINT FK_TRANSACTION_R_BANK_ACCOUNT REFERENCES BANK_ACCOUNT (id),
    transaction_type_id BIGINT                   NOT NULL
        CONSTRAINT FK_TRANSACTION_R_TRANSACTION_TYPE REFERENCES TRANSACTION_TYPE (id),
    amount              DOUBLE PRECISION         NOT NULL,
    created_on          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

